### ISSUE TITLE
Unable to run CMOR3 without CMIP6_CV.json

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#90]
I am trying to run the [CMIP6 example](https://github.com/PCMDI/cmor/blob/master/Test/test_python_CMIP6_experimentID.py) without specifying a Controlled Vocabularies (CV) file. I removed the `TestTables/CMIP6_CV.json` file and commented the `_control_vocabulary_file` and `_cmip6_option` attributes (described [here](http://cmor.llnl.gov/mydoc_cmip6_user_input/)) in the `Test/test_python_CMIP6_experimentID.json` file, but when I run the example I get the following error during the `cmor.load_table` step:

```
 C Traceback:
! In function: cmor_load_table_internal
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Could not find file: Tables/CMIP6_CV.json
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Can't open table Tables/CMIP6_CV.json
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

Why does CMOR3 try to load `CMIP6_CV.json` when I haven't specified a CV file in the JSON file nor specified that I want to trigger validation?

If I create a `CMIP6_CV.json` file containing just:

```
{
"CV": {
    "required_global_attributes": [],
    }
}
```

I get a `Segmentation fault (core dumped)` message during the `cmor.write` step.

Would it be possible to update CMOR3 so it can be run without specifying a CV file / specifying a minimal CV file?

**Comment by dnadeau4** [comment]
I'll fix the segmentation fault, but what you are doing is so "out-of-the-box".  What are you trying to do?  We set up Control Vocabulary in CMOR for CMIP6 publication in ESGF.  If you disable this, you won't be able to publish.  @taylor13 might be able to help you here.

**Comment by ehogan** [comment]
Apologies again for the lack of background. I have a number of CMIP5 functional tests for the code I am working on and I was trying to create the same output netCDF files that CMOR2 created by using CMOR3. Therefore, I wanted to not specify a list of `required_global_attributes` / specify a minimal list that was relevant to CMIP5 so that I could reproduce the output netCDF files for CMIP5. However, it seems that CMOR3 has hardcoded the name of the CV file in the code.

**Comment by dnadeau4** [comment]
The control vocabulary will verify that all `required_global_attributes` are present before writing the final file.  Other people have created their own ``CV files`` without major issues.  [Input4Mips](https://github.com/PCMDI/input4MIPs-cmor-tables/blob/master/Tables/input4MIPs_CV.json)  [obs4MIPs](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/demo/obs4MIPs_CV.json) for examples.   There is also a documentation about it in the [CMOR web site](http://cmor.llnl.gov/mydoc_cmor3_CV/) example section.

Note: @taylor13 and @durack1 are modifying the data structure for the CV file, and CMOR will need to be modified to handle the new structure.  it will look like the obs4MIPs example.

**Comment by dnadeau4** [comment]
@ehogan were you able to create a `CV file` that works for you?

**Comment by ehogan** [comment]
@dnadeau4 Apologies for the delay in my reply. I am still seeing both the issues I mentioned in my first comment using CMOR 3.1.2. 

With regards to the first issue, I would have expected to be able to run CMOR without specifying a CV file. Is this not the case? If a CV file is required, I was going to suggest changing the error message from `Could not find file: Tables/CMIP6_CV.json` to something like `Please define _control_vocabulary_file in the JSON file for cmor_dataset_json`, but unfortunately this won't be enough; if there happens to be a `CMIP6_CV.json` file in the `Tables` directory, CMOR will read this file, even if the `_control_vocabulary_file` and `_cmip6_option` attributes are missing from the JSON file. So there is definitely a hardcoded `CMIP6_CV.json` somewhere in CMOR. 

With regards to the second issue:

* if I completely remove `experiment_ids`, `institution_ids` or `grid_labels` from the CV file the `Segmentation fault (core dumped)` message is printed during the `cmor.write` step
* if I completely remove `source_ids` from the CV file the error `Your "source_ids" key could not be found in your Control Vocabulary file.(Tables/CMIP5_CV.json)` is printed
* if I remove all entries from `experiment_ids`, `institution_ids`, `grid_labels` and `source_ids` an appropriate error is printed. However, for `source_ids`, the `Segmentation fault (core dumped)` message is also printed

Therefore, if `experiment_ids`, `institution_ids`, `grid_labels` and `source_ids` are required to exist in the CV file, would it be possible for appropriate error messages (instead of `Segmentation fault (core dumped)`) to be printed if they don't exist (and ideally documented somewhere, perhaps on the [CMOR web site](http://cmor.llnl.gov/mydoc_cmor3_CV/) you linked to before?). All other entries in the CV file appear to be optional since I can remove them without any issues. I can also remove all the entries associated with an `experiment_id` without any issues.

Other than the above, I have had no problems with customising the CV file :)

**Comment by dnadeau4** [comment]
Emma,

Thanks for this issue.  I fixed the program in branch [cmor-3.1.3](https://github.com/PCMDI/cmor/blob/cmor-3.1.3/Test/cmor_speed_and_compression.json#L3) so it does not ``Segmentation fault (core dumped)``. 

I also created a [CV_minimal.json](https://github.com/PCMDI/cmor/blob/cmor-3.1.3/TestTables/CMIP6_CV_minimal.json) file.  

The code is now more robust, I did not expect CMIP6 modelers to play with the ``CMIP6_CV`` file. 

BTW: other projects do not need to check source_id, Experiment_id, grids and further_info_url since they do not define the ``_cmip6_option`` key in their ``user input JSON`` file.   

* For CMIP5, make sure you don't specify ``_cmip6_otion`` in our ``user input JSON`` file.

Look [here](https://github.com/PCMDI/cmor/blob/cmor-3.1.3/Src/cmor.c#L2738-L2744) and [here](https://github.com/PCMDI/cmor/blob/cmor-3.1.3/include/cmor.h#L179)

* Here is an example for [CMIP6](https://github.com/PCMDI/cmor/blob/cmor-3.1.3/Test/cmor_speed_and_compression.json#L3)

**Comment by dnadeau4** [comment]
If you don't specify ``_cmip6_option`` in your ``user input JSON`` file.  This is the minimal CV file.
I need to check the institution_ids no matter what project.  
{
"CV": { "institution_ids": { "BNU":"" } }
}

**Comment by ehogan** [comment]
Thanks @dnadeau4 :) I tested your `cmor-3.1.3` branch but unfortunately I am still seeing the `Could not find file: Tables/CMIP6_CV.json` error when the `_control_vocabulary_file` is missing from the JSON file, and also the `Segmentation fault (core dumped)` message when I remove all entries from `source_ids`.

Thank you for the information about `_cmip6_option`, it was very useful :)

**Comment by dnadeau4** [comment]
Emma,  I must have missed something for source_ids.  I added the following code: [source_ids](https://github.com/PCMDI/cmor/blob/cmor-3.1.3/Src/cmor_CV.c#L525-L534) 

 As for `_control_vocabulary`,  I need to ask `PCMDI` if I can make it optional.  Everybody seems to like the validation for file consistency between projects.

**Comment by dnadeau4** [comment]
_control_vocabulary is mandatory.
